function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = -5; // block
	global.__objectDepths[1] = 0; // conveyor
	global.__objectDepths[2] = 5; // platform
	global.__objectDepths[3] = -10; // vineL
	global.__objectDepths[4] = -10; // vineR
	global.__objectDepths[5] = 0; // water
	global.__objectDepths[6] = 0; // water2
	global.__objectDepths[7] = 0; // water3
	global.__objectDepths[8] = 5; // gravityUp
	global.__objectDepths[9] = 5; // gravityDown
	global.__objectDepths[10] = 5; // spikeUp
	global.__objectDepths[11] = 5; // spikeDown
	global.__objectDepths[12] = 5; // spikeLeft
	global.__objectDepths[13] = 5; // spikeRight
	global.__objectDepths[14] = 0; // spikeUpMini
	global.__objectDepths[15] = 0; // spikeDownMini
	global.__objectDepths[16] = 0; // spikeLeftMini
	global.__objectDepths[17] = 0; // spikeRightMini
	global.__objectDepths[18] = 0; // killer
	global.__objectDepths[19] = 5; // apple
	global.__objectDepths[20] = -20; // blood
	global.__objectDepths[21] = 0; // bloodEmitter
	global.__objectDepths[22] = 0; // bullet
	global.__objectDepths[23] = 0; // player
	global.__objectDepths[24] = 0; // playerStart
	global.__objectDepths[25] = 5; // trigCherry
	global.__objectDepths[26] = 0; // trigger
	global.__objectDepths[27] = 0; // roomSwitch
	global.__objectDepths[28] = 0; // movingTriggerBase
	global.__objectDepths[29] = 0; // intersectSwitch
	global.__objectDepths[30] = 0; // saveBlocker
	global.__objectDepths[31] = 5; // savePoint
	global.__objectDepths[32] = 1337; // world
	global.__objectDepths[33] = 0; // bossController
	global.__objectDepths[34] = 4; // bossRoomBlock
	global.__objectDepths[35] = 0; // trail
	global.__objectDepths[36] = 0; // introSpawner
	global.__objectDepths[37] = 1; // introCircler
	global.__objectDepths[38] = 3; // introWrapper
	global.__objectDepths[39] = 0; // introAppleDown
	global.__objectDepths[40] = 0; // introWall
	global.__objectDepths[41] = 4; // introPinkCircle
	global.__objectDepths[42] = 4; // introEndBGColourer
	global.__objectDepths[43] = 4; // part2BG
	global.__objectDepths[44] = 2; // part2BGEff
	global.__objectDepths[45] = 0; // part2TopSpawner
	global.__objectDepths[46] = 0; // part2RightSpawner
	global.__objectDepths[47] = 0; // part2AppleDown
	global.__objectDepths[48] = 0; // part2AppleCurve
	global.__objectDepths[49] = 0; // part2AppleWall
	global.__objectDepths[50] = 2; // part2WooshEff
	global.__objectDepths[51] = 0; // part2Aimed
	global.__objectDepths[52] = 0; // part2BigFaller
	global.__objectDepths[53] = 0; // part3CircleController
	global.__objectDepths[54] = 2; // part3CircleApple
	global.__objectDepths[55] = 1; // part3CircleCenter
	global.__objectDepths[56] = 0; // part3SideSpawner
	global.__objectDepths[57] = 0; // part3SidewaysApple
	global.__objectDepths[58] = 2; // part3InwardApple
	global.__objectDepths[59] = 0; // part3ScreenBump
	global.__objectDepths[60] = 0; // part3end1apple
	global.__objectDepths[61] = 1; // part3end1bar
	global.__objectDepths[62] = 0; // part3end3big
	global.__objectDepths[63] = 0; // part3end3small
	global.__objectDepths[64] = 0; // part3end4star1
	global.__objectDepths[65] = 0; // part3end4star2
	global.__objectDepths[66] = 0; // part3end4star3
	global.__objectDepths[67] = 0; // part3end5BurstStarter
	global.__objectDepths[68] = -1; // part3end5tracker
	global.__objectDepths[69] = -1; // part3end5curver
	global.__objectDepths[70] = 0; // part3end6UpSpawner
	global.__objectDepths[71] = 0; // part3end6up
	global.__objectDepths[72] = 0; // part3end6ShootoutApple
	global.__objectDepths[73] = 0; // part3EndFlash
	global.__objectDepths[74] = 0; // part4BackgroundFruitEff
	global.__objectDepths[75] = 21; // part4BackgroundEff
	global.__objectDepths[76] = -6; // part4FakeBlockEff
	global.__objectDepths[77] = 0; // part4BRSpawner
	global.__objectDepths[78] = 0; // part4TRSpawner
	global.__objectDepths[79] = -7; // part4Apple
	global.__objectDepths[80] = 0; // part4LineAimer
	global.__objectDepths[81] = 0; // part4WallsController
	global.__objectDepths[82] = -7; // part4WallApple
	global.__objectDepths[83] = -8; // part4p2big
	global.__objectDepths[84] = 0; // part4p2FloorApple
	global.__objectDepths[85] = -8; // part4p2fall
	global.__objectDepths[86] = -7; // part4p2LineApple
	global.__objectDepths[87] = 0; // part4p2LineController
	global.__objectDepths[88] = -7; // part4p2StarApple
	global.__objectDepths[89] = -10; // part4p2ZoomEff
	global.__objectDepths[90] = -10; // part4p3CircleApple
	global.__objectDepths[91] = 0; // part4p3Controller
	global.__objectDepths[92] = -1; // part5ZoomController


	global.__objectNames[0] = "block";
	global.__objectNames[1] = "conveyor";
	global.__objectNames[2] = "platform";
	global.__objectNames[3] = "vineL";
	global.__objectNames[4] = "vineR";
	global.__objectNames[5] = "water";
	global.__objectNames[6] = "water2";
	global.__objectNames[7] = "water3";
	global.__objectNames[8] = "gravityUp";
	global.__objectNames[9] = "gravityDown";
	global.__objectNames[10] = "spikeUp";
	global.__objectNames[11] = "spikeDown";
	global.__objectNames[12] = "spikeLeft";
	global.__objectNames[13] = "spikeRight";
	global.__objectNames[14] = "spikeUpMini";
	global.__objectNames[15] = "spikeDownMini";
	global.__objectNames[16] = "spikeLeftMini";
	global.__objectNames[17] = "spikeRightMini";
	global.__objectNames[18] = "killer";
	global.__objectNames[19] = "apple";
	global.__objectNames[20] = "blood";
	global.__objectNames[21] = "bloodEmitter";
	global.__objectNames[22] = "bullet";
	global.__objectNames[23] = "player";
	global.__objectNames[24] = "playerStart";
	global.__objectNames[25] = "trigCherry";
	global.__objectNames[26] = "trigger";
	global.__objectNames[27] = "roomSwitch";
	global.__objectNames[28] = "movingTriggerBase";
	global.__objectNames[29] = "intersectSwitch";
	global.__objectNames[30] = "saveBlocker";
	global.__objectNames[31] = "savePoint";
	global.__objectNames[32] = "world";
	global.__objectNames[33] = "bossController";
	global.__objectNames[34] = "bossRoomBlock";
	global.__objectNames[35] = "trail";
	global.__objectNames[36] = "introSpawner";
	global.__objectNames[37] = "introCircler";
	global.__objectNames[38] = "introWrapper";
	global.__objectNames[39] = "introAppleDown";
	global.__objectNames[40] = "introWall";
	global.__objectNames[41] = "introPinkCircle";
	global.__objectNames[42] = "introEndBGColourer";
	global.__objectNames[43] = "part2BG";
	global.__objectNames[44] = "part2BGEff";
	global.__objectNames[45] = "part2TopSpawner";
	global.__objectNames[46] = "part2RightSpawner";
	global.__objectNames[47] = "part2AppleDown";
	global.__objectNames[48] = "part2AppleCurve";
	global.__objectNames[49] = "part2AppleWall";
	global.__objectNames[50] = "part2WooshEff";
	global.__objectNames[51] = "part2Aimed";
	global.__objectNames[52] = "part2BigFaller";
	global.__objectNames[53] = "part3CircleController";
	global.__objectNames[54] = "part3CircleApple";
	global.__objectNames[55] = "part3CircleCenter";
	global.__objectNames[56] = "part3SideSpawner";
	global.__objectNames[57] = "part3SidewaysApple";
	global.__objectNames[58] = "part3InwardApple";
	global.__objectNames[59] = "part3ScreenBump";
	global.__objectNames[60] = "part3end1apple";
	global.__objectNames[61] = "part3end1bar";
	global.__objectNames[62] = "part3end3big";
	global.__objectNames[63] = "part3end3small";
	global.__objectNames[64] = "part3end4star1";
	global.__objectNames[65] = "part3end4star2";
	global.__objectNames[66] = "part3end4star3";
	global.__objectNames[67] = "part3end5BurstStarter";
	global.__objectNames[68] = "part3end5tracker";
	global.__objectNames[69] = "part3end5curver";
	global.__objectNames[70] = "part3end6UpSpawner";
	global.__objectNames[71] = "part3end6up";
	global.__objectNames[72] = "part3end6ShootoutApple";
	global.__objectNames[73] = "part3EndFlash";
	global.__objectNames[74] = "part4BackgroundFruitEff";
	global.__objectNames[75] = "part4BackgroundEff";
	global.__objectNames[76] = "part4FakeBlockEff";
	global.__objectNames[77] = "part4BRSpawner";
	global.__objectNames[78] = "part4TRSpawner";
	global.__objectNames[79] = "part4Apple";
	global.__objectNames[80] = "part4LineAimer";
	global.__objectNames[81] = "part4WallsController";
	global.__objectNames[82] = "part4WallApple";
	global.__objectNames[83] = "part4p2big";
	global.__objectNames[84] = "part4p2FloorApple";
	global.__objectNames[85] = "part4p2fall";
	global.__objectNames[86] = "part4p2LineApple";
	global.__objectNames[87] = "part4p2LineController";
	global.__objectNames[88] = "part4p2StarApple";
	global.__objectNames[89] = "part4p2ZoomEff";
	global.__objectNames[90] = "part4p3CircleApple";
	global.__objectNames[91] = "part4p3Controller";
	global.__objectNames[92] = "part5ZoomController";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
